name: Build Cross-Platform Binaries
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile Cython Extensions
        run: |
          cd src/modules
          python setup.py build_ext --inplace

      - name: Build Standalone Executable Directory
        run: |
          pyinstaller --clean --onefile --name basic --icon="assets/logo.ico" --paths="src" --collect-all colorama --collect-all numpy src/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: dist/basic.exe